### PR TITLE
Babywise & Nick2bad4u custom trims

### PR DESCRIPTION
**Pull request by Babywise**
I've created some simple trims and organised the readme in a way to show the default trims and my trims in a different section, i thought it looked nice for the main page and format could be reused for other contributors to keep the main page readme nice and neat

I will be adding more trims in the future (the readme table under the babywise section has spacing placeholders for future additions)

If future contributors use the table format i've used, try not to exceed 7 columns or the table will not fit correctly (depending on username length -> see readme for reference)

### CODE REVIEW

**Comment by NathanQuayle** [comment]
Thank you for this! Will take a look through, but at first glance looks very well put together!

**Comment by Babywise** [comment]
Thank you!, i also just added all of the trims that Nick2bad4u added in his issue request, i've committed onto this branch to combine the work

**Review by NathanQuayle — APPROVED** [review]

**Comment by NathanQuayle** [comment]
Thanks again for this! And sorry it took so long. I'm working on something to make it a little easier to see (and upload trims) going forward. :)

**Comment by Babywise** [comment]
No worries! haha sounds good :P, I don't have much experience with runescape plugin dev yet, but I might be able to help out if you need a hand. I'm always happy to help and learn some new things along the way! :) I'm in school for computer science, and the semester is almost over so i'd be more than happy to lend a hand. Im most comfortable in C++ and C#, but ive done a little java and javascript dev as well.

I did already start adding a few new trims locally on my branch while I was waiting for you to approve it, so i might have another pull request with trims coming in again shortly haha

**Comment by Babywise** [comment]
dang, nice job with the website!

**Comment by NathanQuayle** [comment]
Haha, thank you! Just wanted to get something up to try and remove some pain. No longer need to create your own examples. :) 

I'm sorry you spent so much time doing it!

But also, feel free to contribute if you see an issue/improvement. Or reach out if you need a hand with plugin dev. :)

**Comment by Babywise** [comment]
all good haha, I had fun with it :), was actually looking forward to submitting some more :P so i was lookin at ur new instructions ;)

Thanks! Will do! I have a few plugin ideas floating around, i'll reach out when i come up with something concrete!

**Comment by Babywise** [comment]
I would like to ask if you've got any tips or resources for learning node and react for webapps, I have a personal project im working on focusing on both but first i'm in the process of learning them. Ideally i want to deploy it using docker

**Comment by NathanQuayle** [comment]
Honestly, https://react.dev/learn is such a good resource. You'll be up to speed pretty quick. 

I personally wouldn't spend a lot of time getting to know the ins and outs of JavaScript. It's stuff you can pick up as you go. I think just build simple apps, compare them to what others are doing and try to understand why. 

For the most part, React is fairly simple. You just need to understand the 'lifecycles'. What causes a render, what is 'state', etc. 

As for Node, I know barely anything. I just Google it as I go. :) Hahah.

**Comment by Babywise** [comment]
haha alright, that helps, i have been focusing a bit too much on javascript learning, Thanks!

**Comment by Babywise** [comment]
one more question, more about the custom trims, if i did add a markdown file inside of the "babywise" trim folder, would that be ok, or will that cause any problems for you? I love the website integration, but i wanted to also include a small readme inside my trims section just in case someone downloads the trims as a zip, it would have a structure similar to this image, just wanted to ask first
image

**Comment by NathanQuayle** [comment]
Won't cause any issues. It picks up .png, .svg, .jpg & .jpeg files. Everything else is skipped over. :)

**Comment by Babywise** [comment]
sweet :)

**Pull request merged**
